### ISSUE TITLE
リスナの＊＊＊Holder変数を外から見えないようにする

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#670]
**Is your feature request related to a problem? Please describe.**
現在の実装では以下のように`***Holder`変数がpublicになっており、使用時にはメンバ変数を取得して関数を呼び出すようになっているが、これはメンバ変数が外から見えるようになった利点が見当たらないため直してほしい。

```
  class ConnectorListeners
  {
  public:
    /*!
     * @if jp
     * @brief ConnectorDataListenerTypeリスナ配列
     * ConnectorDataListenerTypeリスナを格納
     * @else
     * @brief ConnectorDataListenerType listener array
     * The ConnectorDataListenerType listener is stored.
     * @endif
     */
    ConnectorDataListenerHolder connectorData_[CONNECTOR_DATA_LISTENER_NUM];
    /*!
     * @if jp
     * @brief ConnectorListenerTypeリスナ配列
     * ConnectorListenerTypeリスナを格納
     * @else
     * @brief ConnectorListenerType listener array
     * The ConnectorListenerType listener is stored. 
     * @endif
     */
    ConnectorListenerHolder connector_[CONNECTOR_LISTENER_NUM];
  };
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
#643 の仕様変更でConnectorDataListenerHolderをポインタにしたため、#669 のようなメモリリークが発生するようになった。

**Comment by r-kurose** [comment]
#669 の関連箇所
```
Direct leak of 1120 byte(s) in 10 object(s) allocated from:
    #0 0x362f12 in operator new(unsigned long) (/tmp/build/examples/SimpleIO/ConsoleOutComp+0x362f12)
    #1 0x38e9ef in RTC::ConnectorListenersT<RTC::TimedLong>::ConnectorListenersT() /tmp/OpenRTM-aist/src/lib/rtm/ConnectorListener.h:1599:35
    #2 0x382fd4 in RTC::InPort<RTC::TimedLong>::initConnectorListeners() /tmp/OpenRTM-aist/src/lib/rtm/InPort.h:805:25
    #3 0x36b589 in RTC::InPort<RTC::TimedLong>::InPort(char const*, RTC::TimedLong&) /tmp/OpenRTM-aist/src/lib/rtm/InPort.h:122:13
    #4 0x367839 in ConsoleOut::ConsoleOut(RTC::Manager*) /tmp/OpenRTM-aist/examples/SimpleIO/ConsoleOut.cpp:33:5
    #5 0x3745cf in RTC::RTObject_impl* RTC::Create<ConsoleOut>(RTC::Manager*) /tmp/OpenRTM-aist/src/lib/rtm/Factory.h:67:16
    #6 0x7efda31bd4dd in RTC::FactoryCXX::create(RTC::Manager*) /tmp/OpenRTM-aist/src/lib/rtm/Factory.cpp:125:30
    #7 0x7efda3491d14 in RTC::Manager::createComponent(char const*) /tmp/OpenRTM-aist/src/lib/rtm/Manager.cpp:763:21
    #8 0x3986c4 in MyModuleInit(RTC::Manager*) /tmp/OpenRTM-aist/examples/SimpleIO/ConsoleOutComp.cpp:41:19
    #9 0x7efda348393c in RTC::Manager::invokeInitProc() /tmp/OpenRTM-aist/src/lib/rtm/Manager.cpp:2798:9
    #10 0x7efda348294e in RTC::Manager::activateManager() /tmp/OpenRTM-aist/src/lib/rtm/Manager.cpp:338:5
    #11 0x3996fe in main /tmp/OpenRTM-aist/examples/SimpleIO/ConsoleOutComp.cpp:109:12
    #12 0x7efda12b5b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

Direct leak of 1120 byte(s) in 10 object(s) allocated from:
    #0 0x362f12 in operator new(unsigned long) (/tmp/build/examples/SimpleIO/ConsoleOutComp+0x362f12)
    #1 0x7efda34006d0 in RTC::ConnectorListeners::ConnectorListeners() /tmp/OpenRTM-aist/src/lib/rtm/ConnectorListener.cpp:232:31
    #2 0x7efda339b594 in RTC::InPortBase::initConnectorListeners() /tmp/OpenRTM-aist/src/lib/rtm/InPortBase.cpp:1134:25
    #3 0x7efda3384019 in RTC::InPortBase::InPortBase(char const*, char const*) /tmp/OpenRTM-aist/src/lib/rtm/InPortBase.cpp:59:5
    #4 0x36b085 in RTC::InPort<RTC::TimedLong>::InPort(char const*, RTC::TimedLong&) /tmp/OpenRTM-aist/src/lib/rtm/InPort.h:116:9
    #5 0x367839 in ConsoleOut::ConsoleOut(RTC::Manager*) /tmp/OpenRTM-aist/examples/SimpleIO/ConsoleOut.cpp:33:5
    #6 0x3745cf in RTC::RTObject_impl* RTC::Create<ConsoleOut>(RTC::Manager*) /tmp/OpenRTM-aist/src/lib/rtm/Factory.h:67:16
    #7 0x7efda31bd4dd in RTC::FactoryCXX::create(RTC::Manager*) /tmp/OpenRTM-aist/src/lib/rtm/Factory.cpp:125:30
    #8 0x7efda3491d14 in RTC::Manager::createComponent(char const*) /tmp/OpenRTM-aist/src/lib/rtm/Manager.cpp:763:21
    #9 0x3986c4 in MyModuleInit(RTC::Manager*) /tmp/OpenRTM-aist/examples/SimpleIO/ConsoleOutComp.cpp:41:19
    #10 0x7efda348393c in RTC::Manager::invokeInitProc() /tmp/OpenRTM-aist/src/lib/rtm/Manager.cpp:2798:9
    #11 0x7efda348294e in RTC::Manager::activateManager() /tmp/OpenRTM-aist/src/lib/rtm/Manager.cpp:338:5
    #12 0x3996fe in main /tmp/OpenRTM-aist/examples/SimpleIO/ConsoleOutComp.cpp:109:12
    #13 0x7efda12b5b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
```

**Comment by Nobu19800** [comment]
#682 で修正済みのため閉じます。
